name: GitHub CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Set up JDK
        uses: actions/setup-java@v2.3.1
        with:
          distribution: 'temurin'
          java-version: 8

      - name: Build with Maven
        run: mvn install -e -B -V
