name: GitHub CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup JDK
        uses: actions/setup-java@v3.1.1
        with:
          distribution: 'temurin'
          java-version: 8

      - name:  Setup Maven
        uses: stCarolas/setup-maven@v4.2
        with:
          maven-version: 3.8.4

      - name: Build with Maven
        run: mvn verify -e -B -V
